import {useState} from 'react';
import {assortment,faqs,processSteps,reviews} from '../data';
import {Button,MessengerLinks,Placeholder,Section} from './Common';
const bullets=(items:string[])=><ul>{items.map(x=><li key={x}>{x}</li>)}</ul>;
export function MainSections(){const[open,setOpen]=useState<number|null>(null);return <>
<Section><h2>Как происходит подбор</h2><div className="four-grid">{processSteps.map((x,i)=><article className="process card" key={x[0]}><Placeholder name={`process-0${i+1}.jpg`}/><b>{x[0]}</b><p>{x[1]}</p></article>)}</div></Section>
<Section className="assort"><h2>Большой ассортимент</h2><div className="six-grid">{assortment.map((x,i)=><article key={x}><Placeholder name={`assortment-0${i+1}.jpg`}/><b>{x}</b></article>)}</div><p className="center">Подберём идеальный вариант под ваш запрос и бюджет</p></Section>
<Section className="tinted"><div className="split"><Placeholder name="quality-main.jpg"/><div><h2>Качество, которому можно доверять</h2>{bullets(['100% натуральные славянские волосы','Мягкие, плотные, без силикона и обработки','Не путаются, легко укладываются','Служат долго при правильном уходе','Каждая партия проходит тщательный отбор'])}<Button id="quality_quiz">Подобрать волосы из наличия</Button></div></div></Section>
<Section><div className="price-layout"><div><h2>Цены</h2><div className="price-grid">{[['Срезы','от 12 000 ₽'],['Капсулы','от 12 500 ₽'],['Длина 40–70 см','от 12 000 ₽']].map(x=><article className="card" key={x[0]}><b>{x[0]}</b><strong>{x[1]}</strong></article>)}</div><small>Индивидуальный подбор под ваш бюджет и задачу</small></div><Placeholder name="pricing-master.jpg"/></div></Section>
<Section><div className="b2b">{[['Для мастеров и студий',['Индивидуальный подход','Поддержка и консультации','Выгодные условия для профессионалов','Рекомендации по подбору для клиентов'],'Работаем с мастерами'],['Для опта',['Оптовые цены','Большие объёмы в наличии','Гибкие условия сотрудничества','Быстрая комплектация заказов'],'Сотрудничать оптом']].map((x,i)=><article className="card b2b-card" key={x[0] as string}><Placeholder name={`b2b-0${i+1}.jpg`}/><div><h2>{x[0]}</h2>{bullets(x[1] as string[])}<Button id={i?'wholesale':'masters'}>{x[2] as string}</Button></div></article>)}</div></Section>
<Section className="offers"><div className="panel"><h2>Спецпредложения</h2><div className="four-grid icons">{['Скидки для постоянных клиентов','Подарки при крупных заказах','Индивидуальные условия для студий и салонов','Акции на определённые оттенки и длины'].map(x=><div key={x}><i>✦</i><span>{x}</span></div>)}</div><Button id="special_offer">Узнать актуальные предложения</Button></div></Section>
<Section><h2>Отзывы и доверие</h2><div className="reviews">{reviews.map(x=><article className="card" key={x[0]}><div className="avatar">{x[0][0]}</div><b>{x[0]}</b><small>{x[1]}</small><p>{x[2]}</p></article>)}</div><div className="dots">● ◦ ◦ ◦</div></Section>
<Section><div className="split delivery"><Placeholder name="delivery-box.jpg"/><div><h2>Доставка</h2>{bullets(['По России — 1–4 дня','Надёжная упаковка','Отправляем СДЭК и другими удобными службами','Возможность отслеживания заказа'])}<Button id="delivery">Узнать стоимость и сроки</Button></div></div></Section>
<Section><h2>Вопросы и ответы</h2><div className="faq">{faqs.map((x,i)=><article key={x[0]}><button aria-expanded={open===i} onClick={()=>setOpen(open===i?null:i)}><b>{x[0]}</b><span>{open===i?'−':'⌄'}</span></button>{open===i&&<p>{x[1]}</p>}</article>)}</div></Section>
<footer className="final" id="contacts"><div className="container"><div><h2>Подберём натуральные славянские волосы именно под ваш запрос</h2><p>Просто отправьте фото и скажите, что вам нужно — и мы подберём идеальные варианты из наличия и отправим реальные фото и видео.</p></div><div><Button id="final_quiz">Подобрать варианты из наличия</Button><MessengerLinks/></div></div></footer>
</>}
